### ISSUE TITLE
Upgrading to latest version

### ISSUE THREAD

**Issue by behrad** [ckrey/MQTT-Client-Framework#86] opened 2016-01-03 22:22 UTC
When upgrading to latest I found that API has changed, but found no upgrade docs...

I changed `initWithClientId` &  `connectToHost` to 

```
_mqttSession = [[MQTTSession alloc] init];
[_mqttSession setDelegate:self];
_mqttSession.clientId = self.mqttClientId;
_mqttSession.userName = self.username;
_mqttSession.password = self.password;
_mqttSession.keepAliveInterval = 60.0f;
_mqttSession.cleanSessionFlag = false;

if( self.usingSSLConnection ) {
                MQTTSSLSecurityPolicyTransport *sslSecPolTransport = [[MQTTSSLSecurityPolicyTransport alloc] init];
                sslSecPolTransport.host = _develop ? kMQTTLocalAddress : kMQTTAddress;
                sslSecPolTransport.port = _develop ? kMQTTLocalPort : (self.usingSSLConnection?kMQTTSSLPort:kMQTTPort);
//                sslSecPolTransport.tls = [parameters[@"tls"] boolValue];
//                sslSecPolTransport.certificates = [MQTTTestHelpers clientCerts:parameters];
                _mqttSession.transport = sslSecPolTransport;
            } else {
                MQTTCFSocketTransport *cfSocketTransport = [[MQTTCFSocketTransport alloc] init];
                cfSocketTransport.host = _develop ? kMQTTLocalAddress : kMQTTAddress;
                cfSocketTransport.port = _develop ? kMQTTLocalPort : (self.usingSSLConnection?kMQTTSSLPort:kMQTTPort);
                _mqttSession.transport = cfSocketTransport;
            }

[_mqttSession connect];           
```

but no success! What am I missing to set the host/port properly!?

**Comment by ckrey** [comment] 2016-01-03 22:32
if you are using [[MQTTSession alloc] initWith... and connectTo everything is taken care of with no intended change to the API.
The interface has moved to MQTTSessionLegacy.h/m.

What is new is the MQTTTransport protocol, which is documented in dist/docs folder and in the relevant .h files.

When you do [[MQTTSession alloc] init], you need to create an MQTTTransport, which can either be an
MQTTCFSocketTransport,
MQTTSSLSecurityPolicy, or
MQTTWebsocketTransport
and assign it to MQTTSession.transport.

You are right to have a look at MQTTTestHelpers, where you can see a few examples.

**Comment by behrad** [comment] 2016-01-03 22:40
Thank you for your fast responses as always @ckrey 
I took the above snippet from MQTTTestHelpers exactly, but client is being disconnected, I will double check the snippet. However you are telling me that using `MQTTSessionLegacy` I'm not losing anything. right?

**Comment by ckrey** [comment] 2016-01-03 22:41
yes, and if you include MQTTClient.h, all the headers are already included.

**Comment by behrad** [comment] 2016-01-03 22:48
Great.

then please let me ask about another issue in the same topic here, not to create another one.
We are facing occasional hangs/freezes when launching our app, when the client is trying to connect/subscribe and it has already offline messages pending in the server. This happens with slow network connections or slow devices. I was unable to detect the source of this... but moved all operations inside `async_dispatch`. no success!

**Comment by ckrey** [comment] 2016-01-03 22:57
This is a typical problem when too many messages are queued up in the broker and the client is flooded with these messages.

To avoid this, move the MQTTSession to a separate thread (remember to execute UI updates on the main thread). Still the processing of the incoming data flood does keep the app busy:

a) I suggest to lower the inflight window size on the server so the server sends out only a smaller number of messages without acknowledged.

b) You may limit the effect by setting the maxWindowSize parameter on the client side to a smaller value too. If the server sends more than maxWindowSize messages before acknowledged, the client throws them away. The server will retry to send these messages after a while.

**Comment by behrad** [comment] 2016-01-03 23:01
> move the MQTTSession to a separate thread

Does this happens by setting a different `runLoop` in the session? I'm already calling MQTTSession methods inside `dispatch_async`

This is happening with 3, 4 offline qos=1 messages! I don't believe this numbers are large enough for this to be an issue @ckrey

**Comment by ckrey** [comment] 2016-01-03 23:09
No, 3 or 4 messages shouldn't be a problem, I was thinking about hundreds...

There is are examples in MQTTTestMultithreading.m for multi threaded, multi session, synchron and asynchron setups.

I have a real world example here: https://github.com/owntracks/OwnTracksCTRL/blob/master/OwnTracksCTRL/OwnTracksCTRL/StatefullThread.m
Small and clear

**Comment by behrad** [comment] 2016-01-04 06:26
Just swapping `MQTTSession.h` via `MQTTSessionLegacy.h` and using my old code facing an error:
```
[MQTTSession initWithClientId:userName:password:keepAlive:cleanSession:runLoop:forMode:]: unrecognized selector sent to instance 0x15d999a0
2016-01-04 09:51:20.106 client[1175:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MQTTSession initWithClientId:userName:password:keepAlive:cleanSession:runLoop:forMode:]: unrecognized selector sent to instance 0x15d999a0'
*** First throw call stack:
```

**Comment by ckrey** [comment] 2016-01-04 12:00
Please check if you included all .m files in your build.

I suggest to integrate the package using CocoaPods. This automatically takes care of such things.

**Comment by behrad** [comment] 2016-01-04 12:59
We are including MQTTClient sources into our static framework! Can this happen using CocoaPods?

**Comment by accfews** [comment] 2016-01-04 13:23
Through this discussion readme.md seems obsolete

**Comment by behrad** [comment] 2016-01-06 12:19
I'm still using the older version of MQTTClient,  However when I put `connectToHost` inside dispatch_async (or operationQueue) within another thead, MQTTClients seems to freeze and doesn't connect !???

**Comment by ckrey** [comment] 2016-01-13 09:08
Can you give me some more details about your threading model so I can try to reproduce/fix the problem. A simple test case that fails would be ideal.

On the other hand `connectToHost`does not block, so there is no need from MQTTClient to put it into a `dispatch_async`.

**Comment by ckrey** [comment] 2017-07-22 11:24
@behrad is this still an issue?

**Closed** 2017-08-02 17:34 UTC
Labels: no activity, question
