### ISSUE TITLE
CleanSession not working?

### ISSUE THREAD

**Issue by ertanden** [ckrey/MQTT-Client-Framework#81] opened 2015-12-29 10:36 UTC
I'm using a custom session manager which disconnect/re-connects with app going to background/foreground. It's basically similar to `MQTTSessionManager`, but I send a message just before "closing" the MQTTSession. Say the message is on topic `status` and content is `offline`. Any topic I publish is with QoS Exactly Once.

The problem is, when the app returns to foreground a re-connect with `cleanSession=YES` is performed. Then after connection is successful I sent a message on topic `status` and content `available`. But somehow the last message I receive is a status with `offline`, which is strange. 

So the order of events:

```
send status: offline
disconnect
re-connect with cleanSession=YES
send status: available
receive own status: available (I do also subscribe to `status` topic, so receive what I publish)
receive own status: offline
```

I just don't understand where the last offline is coming from! Any ideas?

**Comment by ckrey** [comment] 2015-12-29 13:42
do you `retain`ing the statis messages?

**Comment by ertanden** [comment] 2015-12-29 13:48
Yes, all status messages are `retained`. But, still I expect the last published `available` status to be received, instead of `offline`.

**Comment by ertanden** [comment] 2015-12-29 13:50
By the way, now I resolved the problem for myself like this:

```
send status: offline
wait until the offline message is delivered (using `messageDelivered` callback)
disconnect
re-connect with cleanSession=YES
send status: available
receive own status: available
````

But still, I don't know the reason why an `offline` was being received out of nowhere at the end.

**Comment by ckrey** [comment] 2015-12-29 14:30
the retained message (which I think in your case is 'offline' is send from the broker as soon as it receives the SUBSCRIBE. Do you subcribe prior to sending the initial status message?

**Comment by ertanden** [comment] 2015-12-30 13:26
When I receive `MQTTSessionEventConnected` event, I send an `available` status message and then subscribe to `status`.

Still, shouldn't the last message I receive be `available` ?

**Comment by ckrey** [comment] 2015-12-30 14:10
I wonder why you are getting your `available`status at all b/c you are SUBSCRIBE after PUBLISH.
It might be caused by the PUBLISH with QOS2 needs 2 round trips but the SUBSCRIBE only one.

Do you have a server log ?
```
log_type all
connection_messages true
log_timestamp true
```
or you may implement the unobstrusive low level MQTTSession callbacks
```
- (void)sending:
- (void)received:
```

**Comment by ckrey** [comment] 2016-07-07 07:19
@ertanden did you resolve the issue? Can we close the issue?

**Comment by ckrey** [comment] 2017-07-22 11:22
closed b/c no reaction since more than a year

**Closed by ckrey** 2017-07-22 11:22 UTC
Labels: question
